{
 "title": "Final",
 "time": { "from": "2021-02-27T12:26:49.631Z", "to": "2021-02-27T15:12:55.057Z" },
 "panels": [
  {
   "title": "Data  dari sensor",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "humidity", "label": "Kelembapan " }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Dalam",
     "select": [
      [
       { "params": [ "T_Dalam" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "T_Dalam" ], "type": "alias" }
      ],
      [
       { "params": [ "H_Dalam" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "H_Dalam" ], "type": "alias" }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Luar",
     "select": [
      [
       { "params": [ "T_Luar" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "T_Luar" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Temperatur",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 4, "x": 16, "y": 0 },
   "targets": [
    {
     "alias": "Dalam",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Dalam",
     "select": [
      [
       { "params": [ "T_Dalam" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Luar",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Luar",
     "query": "SELECT last(\"T_Luar\") AS \"Luar\" FROM \"Luar\" WHERE $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "T_Luar" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "PMV",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "PMV",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "pmv",
     "select": [
      [
       { "params": [ "PMV" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Daya",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 5 },
   "format": "watt",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "pzem",
     "select": [
      [
       { "params": [ "P" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Power" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "PMV",
   "type": "graph",
   "gridPos": { "h": 6, "w": 16, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "PMV",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "pmv",
     "select": [
      [
       { "params": [ "PMV" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "PMV" ], "type": "alias" }
      ],
      [
       { "params": [ "PMV" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "150" ], "type": "moving_average" },
       { "params": [ "mov_avg_PMV" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Daya ",
   "type": "graph",
   "gridPos": { "h": 6, "w": 16, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "watt", "label": "Daya" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "pzem",
     "select": [
      [
       { "params": [ "P" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Power (W))" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Tegangan, Arus, dan Daya",
   "type": "graph",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "pzem",
     "select": [
      [
       { "params": [ "P" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Power (W))" ], "type": "alias" }
      ],
      [
       { "params": [ "I" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Arus (A)" ], "type": "alias" }
      ],
      [
       { "params": [ "V" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Tegangan (V)" ], "type": "alias" }
      ]
     ]
    }
   ]
  }
 ]
}